<center>
  <h1> CSCI-P556 Applied Machine Learning</h1>
  <h1> CSCI-P556</h1>
  <h1> Assignment 0 </h1>
</center>
---





## Instructions
1. Please read the questions carefully and give your responses in the correct place.
2. Do not change the contents of the notebook except when adding your reponses or where it is explicitly mentioned.
3. Whenever you are asked to write a function and the argument names are mentioned in the question, you have to assume that while testing these arguments will be defined elsewhere in the notebook. 
3. You are allowed to define test arguments of the same name in the respective code block in order to test your functions.
4. If you have been asked to print or plot something, you are supposed to print/plot it and not just provide a function. This is grad school, we expect the plots to be labeled.
5. You should save your notebook along with the outputs and submit it



In [0]:
# For this assignment you'll need to import the following libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Question 1 (5 points)

Consider a 4x4 numpy array as shown
$$\begin{bmatrix}1 & 2 & 3 & 4\\5 & 6 & 7 & 8\\9 & 10 & 11 & 12\\13 & 14 & 15 & 16\end{bmatrix}$$

1. Create the above matrix with one line of code and name it $a$. Print the matrix.
2. Write code to select its principal diagonal (the sequence: 1, 6, 11, 16) in another line. Store this diagonal in $d$. Print $d$
3. Write code to select 4 elements in the center of the array (in this case: 6, 7, 10, 11) and store it in $c$. Print $c$.
4. Replace the diagonal elements by their squares and print the new $a$.

#### Restrictions: 
To make the problem interesting, you are **NOT** allowed to:
- Use the predefined functions or methods, such as the diagonal() method that is available in numpy

In [79]:
a = np.arange(1,17).reshape(4,4)
print("Print array:\n",a)
print("\n")

d = []
for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        if(i == j):
            d.append(a[i][j])
print("Print Diagonal:\n",d)
print("\n")

c = []
for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        if(i == 0 or i == len(a)-1 or j == 0 or j == len(a[0]) - 1):
            continue
        else:
            c.append(a[i][j])
print("Print Center elements:\n",c)
print("\n")
            
for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        if(i == j):
            a[i][j] = a[i][j]*a[i][j]
print("Print squared diagonals:\n", a)
print("\n")

Print array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Print Diagonal:
 [1, 6, 11, 16]


Print Center elements:
 [6, 7, 10, 11]


Print squared diagonals:
 [[  1   2   3   4]
 [  5  36   7   8]
 [  9  10 121  12]
 [ 13  14  15 256]]




## Question 2 (3 points)


Let us make the above question a bit more interesting. The previous problem was easy in the sense that you could hardcode some values and it would work for all 4*4 matrices. What if you didn't know the size of the array $a$. Let us assume it is $n \times n$.
1. Write code that accepts a matrix $a$ as input.
2. Write code to print the diagonal elements of $a$.
3. For any $k$, write code to print the elements which lie in the center $k \times k$ region of the $a$.
4. Be sure to validate that the input and parameters are correct. See the Examples subsection below to see... examples!

#### Note:
- Same restrictions apply as above
- You should assume that only the matrix $a$ and the integer $k$ have been defined elsewhere in the notebook are available to you. Your code will be tested on a number of test cases and should pass them all successfully


#### Examples:
- If we had a matrix such as the one below, with n=3, k=1, the output should be "1" or "[1]". If the user had set the parameter k=2, then an error should be raised because there isn't a 2*2 submatrix that falls directly in the middle of the original matrix.

$$\begin{bmatrix}2 & 2 & 2 \\2 & 1 & 2 \\2 & 2 & 2 \end{bmatrix}$$

- In the case of n=4, k=2, the output should be "[[1, 1], [1, 1]]", or an equivalent representation of those values, such as "1 1 1 1" or [1,1,1,1], etc. See that similar to above, setting the parameter k=1 here doesn't make sense.

$$\begin{bmatrix}2 & 2 & 2 & 2\\2 & 1 & 1 & 2\\2 & 1 & 1 & 2\\2 & 2 & 2 & 2\end{bmatrix}$$

- n=5. Here k can be 1 or 3. If k=1, then it returns [1]. If k=3, then it returns [[2,2,2], [2,1,2],[2,2,2]].

$$\begin{bmatrix}3 & 3 & 3 & 3 & 3\\3 & 2 & 2 & 2 & 3\\3 & 2 & 1 & 2 & 3\\3 & 2 & 2 & 2 & 3 \\ 3 & 3 & 3 & 3 & 3 \end{bmatrix}$$

In [68]:
### YOUR CODE FOR Q2 GOES HERE
import numpy as np

def matrix(a,k):
    if(a == None or len(a) == 0 ):
        return "Please enter correct matrix"
    if(len(a)!=len(a[0])):
        return "Not a square matrix"
    a = np.array(a)
    d = []
    for i in range(0,len(a)):
        for j in range(0,len(a[0])):
            if(i == j):
                d.append(a[i][j])
    print("Print Diagonal:\n",d)
    print("\n")
    if((len(a)%2 == 0 and k%2 == 0 and k<=len(a) and k!=0) or (len(a)%2 == 1 and k%2 == 1 and k<=len(a) and k!=0) ):
        index1 = int((len(a)-k)/2)
        index2 = int((len(a)+k)/2)
        cantral_matrix = []
        for i in range(index1,index2):
            temp = []
            for j in range(index1,index2):
                temp.append(a[i][j])
            cantral_matrix.append(temp)
        print("Central Matrix is:")    
        print(cantral_matrix)
    else:
        return "Can not extract central matrix"

a = [[3,3,3,3,3],[3,2,2,2,3],[3,2,1,2,3],[3,2,2,2,3],[3,3,3,3,3]]
#a = None
k = 3
matrix(a,k)

Print Diagonal:
 [3, 2, 1, 2, 3]


Central Matrix is:
[[2, 2, 2], [2, 1, 2], [2, 2, 2]]


## Question 3 (6 points)

In this question, we will look at the speedup that vectorization brings to the table. The dot product of two vectors $\overline{a}=[a_1, a_2, \ldots, a_n]$ and $\overline{b}=[b_1, b_2, \ldots, b_n]$  is defined as:
$$ \overline{a} \cdot \overline{b} = \sum_{i=1}^n a_i b_i$$

1. Write a function to calculate the dot product of two lists using `for` loops.
2. Use numpy's functionality to do the same.
3. Find out computation times for arrays of sizes (10,000, 20,0000, ..., 100,000) and plot the two sets of times in a line plot.

In [66]:
## Boilerplate code for Question 3
gen = np.random.RandomState(seed=42)
import timeit
import numpy as np
import matplotlib.pyplot as plt

def time_function(f, *args):
  """
  This is a simple utility function to measure the runtime 
  of a python function. It will return the result of the function
  execution and the time taken to run that function. Any arguments 
  required by the function to run should be passed after the function name.
  INPUT: function name, arg1, arg2, ...
  OUTPUT: Output of the passed function, time taken to run it
  """   
  start = timeit.default_timer()
  ret = f(*args)
  f(*args)
  #f(*args)
  stop = timeit.default_timer()
  return ret, (stop-start)/3

def random_int_array(array_size):
  # The low and high arguments below are used to specify the range of random
  # values that will be used to generate the random integers.
  return np.random.randint(low=0, high=1000000, size=array_size)

def calculate_dot_product(a, b):
    dp = 0
    for i in range(0,len(a)):
        dp+= a[i]*b[i]
    return dp
        
sizes = (10000 * i for i in range(1, 11))
time_a = []
time_b = []
for size in sizes:
  a = gen.rand(size)
  b = gen.rand(size)
  dp1, dp1_time = time_function(calculate_dot_product,a,b)
  dp2, dp2_time = time_function(np.dot,a,b)
  assert(round(dp1,4) == round(dp2,4))
  time_a.append(dp1_time)
  time_b.append(dp2_time)

# Write code to plot the time values
plt.plot(time_a)
plt.xlabel("Array_Size")
plt.plot(time_b)
plt.ylabel("Time")

Text(0, 0.5, 'Time')

## Question 4 (4 points)

We have provided code which loads an interesting dataset about breast cancer in a pandas dataframe variable called `data`. We also provide 5 samples of the dataset.
The breast cancer dataset is loaded into a dataframe called "data" and the "labels" are stored as a dataframe as well.  

Please bear in mind that you cannot actually look at the entire dataset in the notebook since it has many columns. If you want to look at the entire dataframe/dataset, use data.to_csv() to write the data frame to a csv file. For the questions given, you don't actually need to look at the entire dataset. A sample of the data shown in the next block is enough.

Write code to:

1.  Get the total number of samples whose "mean perimeter" is greater than 130.
2.  Group the "worst area" column based on the "labels" and get the maximum "worst area" for each group. In this case, there will be 2 groups since we have only 2 labels.
3.  Get the column which has the minimum sum and subtract each value of that column by its mean. i.e., (column value - mean of the column)

Information about the dataset columns can be found at: http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html

In [72]:
#Starter code. Do not make changes to this code block.

from sklearn.datasets import load_breast_cancer
import pandas as pd
raw_data = load_breast_cancer()

data = pd.DataFrame(raw_data["data"], columns= raw_data["feature_names"])
labels = pd.DataFrame(raw_data["target"], columns = ["target"])
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [73]:
# Code for Question 4.1
total_mp_samples = 0
for dt in data["mean perimeter"]:
    if(dt>130.0):
        total_mp_samples+=1
print(total_mp_samples)

51


In [74]:
# Code for Question 4.2
label1 = []
label2 = []
for dt,lb in zip(data["worst area"],labels["target"]):
    if(lb == 0):
        label1.append(dt)
    else:
        label2.append(dt)
print(max(label1))
print(max(label2))

4254.0
1210.0


In [75]:
# Code for Question 4.3
list1 = list(data)
result = []
min_column = min(data.loc[:,:].sum())
for lb,dt in zip(list1,data.loc[:,:].sum()):
    if(dt == min_column):
        target_column = lb
        break
mean_column = data.loc[:,target_column].mean()
for dt in data[target_column]:
    data[target_column].replace(dt,dt-mean_column,inplace=True)

## Question 5 (7 points)

### Part A

Write a function which takes three inputs and produces a plot using matplotlib. The first two inputs are lists. Each list contains a certain number of tuples. Each tuple in turn contains the $x$ and $y$ co-ordinates of a point. The third input is a stand-alone tuple containing the co-efficients $(a, b, c)$ of a line represented by $ax + by + c = 0$.

The function should plot the first set of points with a red '+' and the second set of points with a blue 'o'. The function should also plot the line in green color. Give a suitable legend and name the axes. If the final tuple isn't provided, the function should gracefully avoid printing the line instead of throwing an error. Feel feel to modify the function definition accordingly.


In [53]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
def plotLineAndPoints(l1, l2, coef = None):
  ### Your code goes here
  for tup in l1:
        plt.plot(tup[0],tup[1],'r+')
  for tup in l2:
        plt.plot(tup[0],tup[1],'bo')
  plt.xlabel("X-co-oridinates")
  plt.ylabel("Y-co-oridinates")
  x_list = []
  y_list = []
  if(coef == None):
    return
  for x in range(0,10):
        x_list.append(x)
        y = -(coef[0]*x+coef[2])/coef[1] 
        y_list.append(y)
  plt.plot(x_list,y_list,linewidth = 3,color = "g")

## Sample Test Cases (We will have many more)
plotLineAndPoints([(1, 2), (2, 3)], [(3, 4), (4, 5)],(-1,2,2))

### Part B

Euclidean distance between two points is defined as by equation (1) on this [Wikipedia page](https://en.wikipedia.org/wiki/Euclidean_distance).

This first part is meant to be written using Markdown math in this cell (double-click it to see the area where you'll write the equation):
  1. Your first task is to write down the Euclidean distance between two points that is defined as by equation (1) on this [Wikipedia page](https://en.wikipedia.org/wiki/Euclidean_distance). It should contain both lines of equation (1).
  
$d(p,q) = d(q,p) = \sqrt{(q_1-p_1)^2+(q_2-p_2)^2+(q_3-p_3)^2+.....+(q_n-p_n)^2}$

$d(p,q) = d(q,p) = \sqrt{\sum_{i=0}^n(q_i-p_i)^2}$

The following parts have to be coded using Python:
  2. Given a point $(x_1,y_1)$ and a radius $r_1$, randomly generate 10 points which lie within the given radius of the given point. The radius is calculated using Euclidean distance. Store them in list $l_1$.
  3. Generate another list $l_2$ for a new point $(x_2, y_2)$ and radius $r_2$
  4. Use the function written in part A to plot the above sets of points.

In [45]:
import math

def euclidean(x1,y1,x2,y2):
    distance = math.sqrt((x2-x1)**2 + (y2-y1)**2)
    return distance
    
x1, y1 = 0, 0
r1 = 10
x2, y2 = 25, 25
r2 = 15

euclidean(x1,y1,x2,y2)

35.35533905932738

In [47]:
import random
import matplotlib.pyplot as plt

x1, y1 = 0, 0
r1 = 10
x2, y2 = 25, 25
r2 = 15
## YOUR CODE GOES HERE
list1 = []
list2 = []
while(1):
    x = random.randrange(-20,50,1)
    y = random.randrange(-20,50,1)
    dist = euclidean(x1,y1,x,y)
    if(dist < r1):
        list1.append((x,y))
    if(len(list1) == 10):
        break

while(1):
    x = random.randrange(0,60,1)
    y = random.randrange(0,60,1)
    dist = euclidean(x2,y2,x,y)
    if(dist < r2):
        list2.append((x,y))
    if(len(list2) == 10):
        break

plotLineAndPoints(list1,list2)